### ISSUE TITLE
Crash on leave midgame

### ISSUE THREAD

**Issue by QuackIsGod** [VixikHD/PrivatePlugins#11]
I left in the middle of a game and the server crashed

steps: 
join game
while game is running leave the server

**Comment by VixikHD** [comment]
To resolve the error, please, upload a crashdump.

**Comment by QuackIsGod** [comment]
[Mon_Sep_26-14.54.57-CDT_2022.log](https://github.com/VixikHD/PrivatePlugins/files/9649938/Mon_Sep_26-14.54.57-CDT_2022.log)

**Comment by darkestcore** [comment]
good job boffy
